### ISSUE TITLE
ANCOVA

### ISSUE THREAD

**Issue by grasshoppermouse** [erikgahner/meaning#1]
For study 1, the authors also report running an ANCOVA with all the demographic variables as controls, including age, which should be pretty similar to your decade variable (unless I don't understand your point). I just replicated their analysis, and did find NineEnd to be significant after controlling for age (and all other the other demographic variables). My F-value was slightly different than theirs, though (not sure why).

Supporting your speculation that folks might not be accurately reporting age, try:

> plot(density(study1$Age)

You'll see bumps at 5-enders and 0-enders, which is pretty typical for age data.

**Comment by erikgahner** [comment]
First, sorry for the late reply. I have been real world travelling for the last couple of weeks.

Second, for Study 1, controlling for age - in the form it is done by the authors - is not identical to controlling for decades. By controlling for age you control for the age trend, but not for the fact that certain end digits are more likely to be represented in certain decades. Furthermore, it is, for example, possible to estimate parameters for both age and decade in a linear model. (And of course, if you control for all ages you are unable to estimate the impact of being a nine-ender.)

Third, thanks! It is funny how people fail to report their real age. One can only speculate how people report their age when you provide an incentive to lie (as may be the case with extramarital affairs).
